### ISSUE TITLE
 Missing argument 1 for..

### ISSUE THREAD

**Issue by ghost** [mohrt/tinymvc-php#6]
How do you pass arguments to a controller through the url?

For my modules controller, I try the following URL:
/modules/index/4

Here's what the index function looks like;

function index ($id) {
 echo $id;
}

I get the following error: 
Error: E_WARNING
Message: Missing argument 1 for Modules_Controller::index(), called in /data/www/tinymvc/sysfiles/TinyMVC.php on line 120 and defined
File: /data/www/tinymvc/myfiles/controllers/modules.php
Line: 5

**Comment by mohrt** [comment]
Use the URI plugin, ships with tinymvc:

http://www.tinymvc.com/documentation/index.php/Plugins:URI
